export interface SecuritySite {
  name: string;
  url: string;
  description: string;
  fullDescription: string;
  category: string;
  tag: 'Free' | 'Freemium' | 'Paid' | 'Free/Pro';
  initials: string;
  color: string;
}

export const categories = [
  'All', 'Vulnerability Database', 'Threat Intelligence', 'Training & CTFs',
  'Certification', 'News & Blogs', 'Tools & Frameworks', 'Community', 'Bug Bounty',
  'Incident Response', 'Malware Analysis',
];

export const tagFilters = ['All', 'Free', 'Freemium', 'Paid'];

export const securitySites: SecuritySite[] = [
  { name: 'CVE Details', url: 'https://cvedetails.com', description: 'Comprehensive CVE database with vulnerability statistics and trending charts', fullDescription: 'Search and browse CVE vulnerabilities by vendor, product, and version. Includes statistics, graphs, and severity rankings.', category: 'Vulnerability Database', tag: 'Free', initials: 'CVE', color: '#ff4455' },
  { name: 'NVD', url: 'https://nvd.nist.gov', description: 'US government official vulnerability database, primary CVE source with CVSS scoring', fullDescription: 'The National Vulnerability Database provides standardized vulnerability data including CVSS scores, CPE configurations, and impact metrics.', category: 'Vulnerability Database', tag: 'Free', initials: 'NVD', color: '#00b4ff' },
  { name: 'Exploit-DB', url: 'https://exploit-db.com', description: 'Archive of public exploits and vulnerable software, maintained by Offensive Security', fullDescription: 'Google Hacking Database, exploit downloads, and vulnerable application archive. Essential resource for penetration testers.', category: 'Vulnerability Database', tag: 'Free', initials: 'EDB', color: '#ff4455' },
  { name: 'VulDB', url: 'https://vuldb.com', description: 'Continuously updated vulnerability database with risk scoring and exploit prices', fullDescription: 'Real-time vulnerability intelligence with EPSS scores, exploit prices, and detailed technical analysis.', category: 'Vulnerability Database', tag: 'Freemium', initials: 'VDB', color: '#cc66ff' },
  { name: 'MITRE ATT&CK', url: 'https://attack.mitre.org', description: 'Globally accessible knowledge base of adversary tactics and techniques', fullDescription: 'Documents common tactics, techniques, and procedures (TTPs) used by threat actors. Essential for threat modeling and detection engineering.', category: 'Threat Intelligence', tag: 'Free', initials: 'ATT', color: '#39ff14' },
  { name: 'AlienVault OTX', url: 'https://otx.alienvault.com', description: 'Open threat intelligence community with pulse sharing and IOC correlation', fullDescription: 'Community-driven threat intelligence platform with 200M+ indicators of compromise. Free API access for integration.', category: 'Threat Intelligence', tag: 'Free', initials: 'OTX', color: '#ff4455' },
  { name: 'VirusTotal', url: 'https://virustotal.com', description: 'Analyze suspicious files, URLs, domains and IPs with 70+ security engines', fullDescription: 'Upload or scan files, URLs, IPs, and domains. Aggregates detection from 70+ antivirus engines and sandboxing services.', category: 'Threat Intelligence', tag: 'Free', initials: 'VT', color: '#39ff14' },
  { name: 'AbuseIPDB', url: 'https://abuseipdb.com', description: 'Report and check IP addresses for malicious activity, spam, and attacks', fullDescription: 'Crowdsourced IP reputation database. Check any IP against 10B+ reports. Free API for integration.', category: 'Threat Intelligence', tag: 'Free', initials: 'AIP', color: '#ff4455' },
  { name: 'TryHackMe', url: 'https://tryhackme.com', description: 'Gamified cybersecurity training with virtual rooms, learning paths, and CTFs', fullDescription: 'Browser-based cybersecurity training platform with guided learning paths, competitive CTFs, and enterprise training solutions.', category: 'Training & CTFs', tag: 'Freemium', initials: 'THM', color: '#39ff14' },
  { name: 'Hack The Box', url: 'https://hackthebox.com', description: 'Penetration testing labs, competitive CTF platform, and enterprise training', fullDescription: 'Community-driven platform with 400+ machines, challenges, and pro labs. Industry-recognized certifications.', category: 'Training & CTFs', tag: 'Freemium', initials: 'HTB', color: '#39ff14' },
  { name: 'PortSwigger Academy', url: 'https://portswigger.net/web-security', description: 'Free web security training from the creators of Burp Suite, with hands-on labs', fullDescription: 'Comprehensive web security curriculum covering OWASP Top 10, advanced topics, and real-world vulnerability research.', category: 'Training & CTFs', tag: 'Free', initials: 'PSA', color: '#ff4455' },
  { name: 'PicoCTF', url: 'https://picoctf.org', description: 'Beginner-friendly CTF platform by Carnegie Mellon University', fullDescription: 'Free CTF competitions and practice problems designed for high school and college students. Great entry point.', category: 'Training & CTFs', tag: 'Free', initials: 'PCT', color: '#00b4ff' },
  { name: 'Cybrary', url: 'https://cybrary.it', description: 'Free and paid cybersecurity courses, certification prep, and career paths', fullDescription: 'Online learning platform with 500+ courses, hands-on labs, and career path recommendations.', category: 'Training & CTFs', tag: 'Freemium', initials: 'CYB', color: '#cc66ff' },
  { name: 'OffSec', url: 'https://offensive-security.com', description: 'OSCP, OSWE, OSEP — industry-leading penetration testing certifications', fullDescription: 'Creators of Kali Linux and the OSCP certification. Hands-on, practical security training.', category: 'Certification', tag: 'Paid', initials: 'OFS', color: '#ff4455' },
  { name: 'SANS', url: 'https://sans.org', description: 'Premium cybersecurity training and GIAC certifications with hands-on labs', fullDescription: 'Gold standard in cybersecurity education. 60+ GIAC certifications and specialized training programs.', category: 'Certification', tag: 'Paid', initials: 'SANS', color: '#00b4ff' },
  { name: 'CompTIA', url: 'https://comptia.org', description: 'Security+, CySA+, Pentest+ — entry to mid-level vendor-neutral certifications', fullDescription: 'Industry-recognized certifications for IT professionals. Vendor-neutral, globally respected.', category: 'Certification', tag: 'Paid', initials: 'CPT', color: '#00b4ff' },
  { name: '(ISC)²', url: 'https://isc2.org', description: 'CISSP, SSCP — gold standard for security management and architecture', fullDescription: 'Global cybersecurity certifications for experienced professionals. CISSP is the most recognized security certification.', category: 'Certification', tag: 'Paid', initials: 'ISC', color: '#ffb300' },
  { name: 'The Hacker News', url: 'https://thehackernews.com', description: 'Trusted cybersecurity news, breach reporting, and threat analysis', fullDescription: 'Daily cybersecurity news, vulnerability disclosures, and threat intelligence reports.', category: 'News & Blogs', tag: 'Free', initials: 'THN', color: '#39ff14' },
  { name: 'BleepingComputer', url: 'https://bleepingcomputer.com', description: 'Security news, malware analysis, ransomware tracking, and tech support', fullDescription: 'Comprehensive cybersecurity news site with malware analysis, ransomware tracking, and technical tutorials.', category: 'News & Blogs', tag: 'Free', initials: 'BC', color: '#ff4455' },
  { name: 'Krebs on Security', url: 'https://krebsonsecurity.com', description: 'Investigative journalism on cybercrime by renowned reporter Brian Krebs', fullDescription: 'Award-winning investigative cybersecurity journalism covering cybercrime, data breaches, and digital security.', category: 'News & Blogs', tag: 'Free', initials: 'KoS', color: '#ffb300' },
  { name: 'Dark Reading', url: 'https://darkreading.com', description: 'Enterprise security news, analysis, and research for CISOs and professionals', fullDescription: 'Enterprise-focused security news and analysis covering risk management, compliance, and emerging threats.', category: 'News & Blogs', tag: 'Free', initials: 'DR', color: '#cc66ff' },
  { name: 'OWASP', url: 'https://owasp.org', description: 'Top 10, ASVS, Cheat Sheets, ZAP — web security standards and tools', fullDescription: 'Open-source web application security project. Creator of OWASP Top 10, ZAP, and numerous security standards.', category: 'Tools & Frameworks', tag: 'Free', initials: 'OWA', color: '#39ff14' },
  { name: 'Nmap', url: 'https://nmap.org', description: 'Network discovery and security auditing tool, the gold standard for port scanning', fullDescription: 'Free and open-source network scanner. Used for host discovery, port scanning, and service detection.', category: 'Tools & Frameworks', tag: 'Free', initials: 'NMP', color: '#39ff14' },
  { name: 'Metasploit', url: 'https://metasploit.com', description: 'Penetration testing framework by Rapid7, largest exploit database integration', fullDescription: 'The world\'s most used penetration testing framework. Free and Pro versions available.', category: 'Tools & Frameworks', tag: 'Free/Pro', initials: 'MSF', color: '#ff4455' },
  { name: 'Burp Suite', url: 'https://portswigger.net/burp', description: 'Industry standard web vulnerability scanner and proxy', fullDescription: 'Essential web security testing tool. Community (free) and Professional editions.', category: 'Tools & Frameworks', tag: 'Freemium', initials: 'BS', color: '#ff4455' },
  { name: 'Wireshark', url: 'https://wireshark.org', description: 'Network protocol analyzer and packet capture, essential for network forensics', fullDescription: 'Free and open-source network protocol analyzer. Deep packet inspection and protocol analysis.', category: 'Tools & Frameworks', tag: 'Free', initials: 'WSK', color: '#00b4ff' },
  { name: 'HackerOne', url: 'https://hackerone.com', description: 'Leading bug bounty platform with active hacker community and disclosure programs', fullDescription: 'Connects organizations with security researchers. $300M+ in bounties paid.', category: 'Bug Bounty', tag: 'Free', initials: 'H1', color: '#39ff14' },
  { name: 'Bugcrowd', url: 'https://bugcrowd.com', description: 'Crowdsourced security platform and bug bounty program management', fullDescription: 'Managed bug bounty programs, vulnerability disclosure, and penetration testing as a service.', category: 'Bug Bounty', tag: 'Free', initials: 'BCD', color: '#39ff14' },
  { name: 'Intigriti', url: 'https://intigriti.com', description: 'European bug bounty and vulnerability disclosure platform', fullDescription: 'Bug bounty platform with a focus on European organizations. Competitive bounty rates.', category: 'Bug Bounty', tag: 'Free', initials: 'INT', color: '#00b4ff' },
  { name: 'Reddit r/netsec', url: 'https://reddit.com/r/netsec', description: 'Technical security discussions, research sharing, and news aggregation', fullDescription: 'Active community of security professionals sharing research, tools, and technical discussions.', category: 'Community', tag: 'Free', initials: 'RS', color: '#ff4455' },
  { name: 'InfoSec Exchange', url: 'https://infosec.exchange', description: 'Mastodon instance for cybersecurity professionals and researchers', fullDescription: 'Decentralized social network for the infosec community. Ad-free, algorithm-free discussion.', category: 'Community', tag: 'Free', initials: 'IE', color: '#cc66ff' },
  { name: 'Packet Storm', url: 'https://packetstormsecurity.com', description: 'Latest security tools, exploits, advisories, and whitepapers', fullDescription: 'Archive of security resources including tools, exploits, advisories, and research papers.', category: 'Tools & Frameworks', tag: 'Free', initials: 'PS', color: '#ffb300' },
  { name: 'Shodan', url: 'https://shodan.io', description: 'Search engine for Internet-connected devices, IoT, and infrastructure', fullDescription: 'The world\'s first search engine for Internet-connected devices. Find servers, routers, webcams, and more.', category: 'Threat Intelligence', tag: 'Freemium', initials: 'SHD', color: '#ff4455' },
  { name: 'Censys', url: 'https://censys.io', description: 'Internet-wide scanning and certificate transparency monitoring', fullDescription: 'Discover and monitor every device on the internet. Free tier available for researchers.', category: 'Threat Intelligence', tag: 'Freemium', initials: 'CNS', color: '#00b4ff' },
  { name: 'MalwareBazaar', url: 'https://bazaar.abuse.ch', description: 'Free malware sample repository for researchers and incident responders', fullDescription: 'Share malware samples with the infosec community. Search by hash, tag, signature, or file type.', category: 'Malware Analysis', tag: 'Free', initials: 'MBZ', color: '#ff4455' },
  { name: 'VirusTotal', url: 'https://virustotal.com', description: 'Analyze suspicious files, URLs, domains and IPs with 70+ security engines', fullDescription: 'Upload or scan files, URLs, IPs, and domains. Aggregates detection from 70+ antivirus engines and sandboxing services.', category: 'Malware Analysis', tag: 'Free', initials: 'VT', color: '#39ff14' },
  { name: 'Any.Run', url: 'https://any.run', description: 'Interactive online malware analysis sandbox with real-time behavior monitoring', fullDescription: 'Upload files and see their behavior in real-time. Network traffic, registry changes, and file modifications visible.', category: 'Malware Analysis', tag: 'Freemium', initials: 'AR', color: '#cc66ff' },
  { name: 'Hybrid Analysis', url: 'https://hybrid-analysis.com', description: 'Free malware analysis service powered by CrowdStrike Falcon Sandbox', fullDescription: 'Submit files for deep analysis. Get detailed reports on behavior, network IOCs, and MITRE ATT&CK mappings.', category: 'Malware Analysis', tag: 'Free', initials: 'HA', color: '#00b4ff' },
  { name: 'SANS Reading Room', url: 'https://sans.org/reading-room', description: 'Free whitepapers and research papers from SANS Institute experts', fullDescription: 'Over 1,500 free cybersecurity research papers covering all aspects of information security.', category: 'Training & CTFs', tag: 'Free', initials: 'SRR', color: '#00b4ff' },
  { name: 'DFIR Training', url: 'https://www.sans.org/dfir/', description: 'Digital Forensics and Incident Response training and resources', fullDescription: 'SANS DFIR division resources including free tools, cheat sheets, and webcasts.', category: 'Training & CTFs', tag: 'Freemium', initials: 'DFR', color: '#ff4455' },
  { name: 'LetsDefend', url: 'https://letsdefend.io', description: 'SOC Analyst training platform with real-world alert simulations', fullDescription: 'Practice responding to real security alerts in a simulated SOC environment. Free tier available.', category: 'Training & CTFs', tag: 'Freemium', initials: 'LDF', color: '#39ff14' },
  { name: 'Detectify', url: 'https://labs.detectify.com', description: 'Security research lab with CVE feeds, exploit database, and writeups', fullDescription: 'Security research lab publishing original vulnerability research and responsible disclosures.', category: 'News & Blogs', tag: 'Free', initials: 'DFT', color: '#ff4455' },
  { name: 'PortSwigger Research', url: 'https://portswigger.net/research', description: 'Cutting-edge web security research from Burp Suite creators', fullDescription: 'Original research on web vulnerabilities, deserialization attacks, and novel exploitation techniques.', category: 'News & Blogs', tag: 'Free', initials: 'PSR', color: '#ff4455' },
  { name: 'ProjectDiscovery', url: 'https://blog.projectdiscovery.io', description: 'Nuclei templates, research, and open-source security tooling blog', fullDescription: 'Blog covering open-source tools like Nuclei, Subfinder, andhttpx with templates and techniques.', category: 'Tools & Frameworks', tag: 'Free', initials: 'PDC', color: '#39ff14' },
  { name: 'Wappalyzer', url: 'https://www.wappalyzer.com', description: 'Identify technology stack of any website — CMS, frameworks, analytics', fullDescription: 'Technology profiling tool to identify what software, frameworks, and services a website uses.', category: 'Tools & Frameworks', tag: 'Freemium', initials: 'WAP', color: '#00b4ff' },
  { name: 'BuiltWith', url: 'https://builtwith.com', description: 'Web technology profiling — find what technologies websites use', fullDescription: 'Comprehensive technology database. Identify CMS, analytics, hosting, and more for any website.', category: 'Tools & Frameworks', tag: 'Freemium', initials: 'BW', color: '#00b4ff' },
];
